disabled_rules:
- trailing_whitespace
- todo
- unused_declaration

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 8
    error: 10

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id

reporter: "xcode"