# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'Story Squad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Story Squad

	pod 'SwiftLint'
	pod "ScalingCarousel"
	pod 'LabelSwitch'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
end
