# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Story Squad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Story Squad

	pod 'SwiftLint'
	pod "ScalingCarousel"
	pod 'LabelSwitch'
	pod 'iCarousel'
	pod 'GoogleAnalytics'
	pod 'Firebase/Analytics'
end
